Feature/27 repeats (#164)
* missing rendertest files added

* [#27] repeat syntax impl

* [#27] repeat feature parser impl
* added rules
* added tests

* fixed boost error: "matches.hpp(830): error C2146: syntax error: missing '>'" on windows

* * repeat :x2| replaced by ^1-n

* * repeats impl.
* volta marks impl.
* render tests added

* * repeat/ignore bug fixed
* dacapo test added

* render tests references added

Co-authored-by: samba <samba@manjaro>
Co-authored-by: Johannes Unger <unger@digitalklang.de>